import type { SessionPathEdge, SessionPathNode, SessionPathViewModel } from './model';

export interface VisibleSessionPath { nodes: SessionPathNode[]; edges: SessionPathEdge[] }
export interface SessionPathExpansionState { collapsedNodeIds: Set<string>; fullyShownNodeIds: Set<string> }
export interface SessionPathFocusState { focused: Set<string>; connected: Set<string>; context: Set<string> }

export function createSessionPathExpansionState(collapsedNodeIds: Iterable<string> = []): SessionPathExpansionState { return { collapsedNodeIds: new Set(collapsedNodeIds), fullyShownNodeIds: new Set() }; }
export function expandPathNodeOneLevel(state: SessionPathExpansionState, nodeId: string, model: SessionPathViewModel): SessionPathExpansionState { const next = clone(state); const node = model.nodes.find((n) => n.id === nodeId); if (node?.expandable) next.collapsedNodeIds.delete(nodeId); return next; }
export function showPathNodeContents(state: SessionPathExpansionState, nodeId: string, model: SessionPathViewModel): SessionPathExpansionState { const next = clone(state); next.collapsedNodeIds.delete(nodeId); for (const child of descendants(nodeId, model)) next.collapsedNodeIds.delete(child.id); next.fullyShownNodeIds.add(nodeId); return next; }
export function hidePathNodeContents(state: SessionPathExpansionState, nodeId: string, model: SessionPathViewModel): SessionPathExpansionState { const next = clone(state); const node = model.nodes.find((n) => n.id === nodeId); if (node?.expandable) next.collapsedNodeIds.add(nodeId); for (const child of descendants(nodeId, model)) next.fullyShownNodeIds.delete(child.id); return next; }
export function sessionPathExpansionActions(state: SessionPathExpansionState, nodeId: string, model: SessionPathViewModel): { expand: boolean; showContents: boolean; hideContents: boolean } { const node = model.nodes.find((n) => n.id === nodeId); if (!node?.expandable) return { expand: false, showContents: false, hideContents: false }; const visible = new Set(buildVisibleSessionPath(model, state).nodes.map((n) => n.id)); const desc = descendants(nodeId, model); return { expand: state.collapsedNodeIds.has(nodeId) || node.childIds.some((id) => !visible.has(id)), showContents: desc.some((n) => !visible.has(n.id)), hideContents: desc.some((n) => visible.has(n.id)) }; }
export function buildVisibleSessionPath(model: SessionPathViewModel, state: SessionPathExpansionState): VisibleSessionPath {
  const byId = new Map(model.nodes.map((node) => [node.id, node]));
  const visibleIds = new Set<string>();
  const visit = (id: string): void => { const node = byId.get(id); if (!node) return; visibleIds.add(id); if (!state.collapsedNodeIds.has(id)) for (const child of node.childIds) visit(child); };
  model.rootNodeIds.forEach(visit);
  const edges = new Map<string, SessionPathEdge>();
  const ordered = model.nodes.filter((node) => visibleIds.has(node.id) && !node.parentGroupId).sort((a, b) => a.firstSourceOrder - b.firstSourceOrder || a.id.localeCompare(b.id));
  for (let i = 1; i < ordered.length; i++) addEdge(edges, { id: `path-visible:${ordered[i - 1].id}->${ordered[i].id}`, source: ordered[i - 1].id, target: ordered[i].id, kind: 'sequence' });
  for (const edge of model.edges) { const source = nearestVisible(edge.source, visibleIds, byId); const target = nearestVisible(edge.target, visibleIds, byId); if (source && target && source !== target) addEdge(edges, { ...edge, id: `${edge.kind}:${source}->${target}`, source, target }); }
  return { nodes: model.nodes.filter((node) => visibleIds.has(node.id)).sort((a, b) => a.firstSourceOrder - b.firstSourceOrder || a.level - b.level || a.id.localeCompare(b.id)), edges: [...edges.values()] };
}
export function searchSessionPath(model: SessionPathViewModel, query: string): string[] { const needle = query.trim().toLocaleLowerCase(); if (!needle) return []; const matches = new Set<string>(); for (const node of model.nodes) { const text = [node.fullLabel, node.displayLabel, node.kind, node.phaseCategory, node.status, node.sourceNodeIds.join(' ')].filter(Boolean).join(' ').toLocaleLowerCase(); if (text.includes(needle)) matches.add(visibleAncestor(node, model).id); } return [...matches].sort((a, b) => (model.nodes.find((n) => n.id === a)?.firstSourceOrder ?? 0) - (model.nodes.find((n) => n.id === b)?.firstSourceOrder ?? 0)); }
export function pathFocusState(model: SessionPathViewModel, nodeId?: string): SessionPathFocusState { const all = new Set(model.nodes.map((n) => n.id)); if (!nodeId) return { focused: new Set(), connected: new Set(), context: all }; const focused = new Set([nodeId]); const connected = new Set<string>(); for (const edge of model.edges) if (edge.source === nodeId || edge.target === nodeId) connected.add(edge.source).add(edge.target); connected.delete(nodeId); return { focused, connected, context: new Set([...all].filter((id) => !focused.has(id) && !connected.has(id))) }; }
function clone(state: SessionPathExpansionState): SessionPathExpansionState { return { collapsedNodeIds: new Set(state.collapsedNodeIds), fullyShownNodeIds: new Set(state.fullyShownNodeIds) }; }
function descendants(id: string, model: SessionPathViewModel): SessionPathNode[] { const byId = new Map(model.nodes.map((node) => [node.id, node])); const result: SessionPathNode[] = []; const visit = (childId: string): void => { const child = byId.get(childId); if (!child) return; result.push(child); child.childIds.forEach(visit); }; byId.get(id)?.childIds.forEach(visit); return result; }
function nearestVisible(id: string, visible: Set<string>, byId: Map<string, SessionPathNode>): string | undefined { let current = byId.get(id); while (current) { if (visible.has(current.id)) return current.id; current = current.parentGroupId ? byId.get(current.parentGroupId) : undefined; } return undefined; }
function addEdge(edges: Map<string, SessionPathEdge>, edge: SessionPathEdge): void { if (!edges.has(edge.id)) edges.set(edge.id, edge); }
function visibleAncestor(node: SessionPathNode, model: SessionPathViewModel): SessionPathNode { const byId = new Map(model.nodes.map((n) => [n.id, n])); let current = node; while (current.parentGroupId) current = byId.get(current.parentGroupId) ?? current; return current; }
