import * as vscode from 'vscode';
import { buildNodeDetails, buildSessionViewModel } from '../opencode/buildSessionViewModel';
import type { NormalizedOpenCodeSession } from '../opencode/model';
import { isWebviewToExtensionMessage } from '../webview/openCodeSessionTrace/model';

export class OpenCodeSessionTracePanel { private static current: OpenCodeSessionTracePanel | undefined; private session?: NormalizedOpenCodeSession; private constructor(private readonly context: vscode.ExtensionContext, private readonly panel: vscode.WebviewPanel, private readonly rawUri: vscode.Uri) { panel.onDidDispose(()=>{ if(OpenCodeSessionTracePanel.current===this) OpenCodeSessionTracePanel.current=undefined; }); panel.webview.onDidReceiveMessage(async (msg: unknown)=>this.handle(msg)); }
  static show(context: vscode.ExtensionContext, session: NormalizedOpenCodeSession, rawUri: vscode.Uri, hideReasoning: boolean): void { if(!this.current) { const scriptRoot = vscode.Uri.joinPath(context.extensionUri, 'dist', 'webview'); this.current = new OpenCodeSessionTracePanel(context, vscode.window.createWebviewPanel('skillMdInspector.openCodeTrace','OpenCode Session Trace',vscode.ViewColumn.Beside,{ enableScripts:true, retainContextWhenHidden:true, localResourceRoots:[scriptRoot] }), rawUri); this.current.panel.webview.html = this.current.html(); } this.current.session=session; this.current.panel.title=`OpenCode Trace: ${session.title}`; this.current.panel.reveal(vscode.ViewColumn.Beside); void this.current.panel.webview.postMessage({ type:'initialize', model: buildSessionViewModel(session, hideReasoning) }); }
  private async handle(msg: unknown): Promise<void> { if(!isWebviewToExtensionMessage(msg) || !this.session) return; if(msg.type==='requestNodeDetails') { const details=buildNodeDetails(this.session,msg.nodeId); await this.panel.webview.postMessage(details ? { type:'nodeDetails', nodeId:msg.nodeId, details } : { type:'showError', message:'Node not found.' }); } else if(msg.type==='openRawSession') await vscode.commands.executeCommand('vscode.open', this.rawUri); else if(msg.type==='copyText') await vscode.env.clipboard.writeText(msg.value); else if(msg.type==='openSkill') { const allowed = new Set(this.session.skills.flatMap((s)=>s.matchingSkills.flatMap((m)=>m.candidates.map((c)=>c.uri)))); if(allowed.has(msg.uri)) await vscode.commands.executeCommand('vscode.open', vscode.Uri.parse(msg.uri)); } }
  private html(): string { const nonce=createNonce(); const script=this.panel.webview.asWebviewUri(vscode.Uri.joinPath(this.context.extensionUri,'dist','webview','openCodeSessionTrace.js')); return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${this.panel.webview.cspSource}; style-src ${this.panel.webview.cspSource} 'unsafe-inline'; script-src 'nonce-${nonce}' ${this.panel.webview.cspSource};"><meta name="viewport" content="width=device-width, initial-scale=1"><title>OpenCode Session Trace</title></head><body><script nonce="${nonce}" src="${script}"></script></body></html>`; }
}
function createNonce(): string { const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'; let n=''; for(let i=0;i<32;i++) n+=chars[Math.floor(Math.random()*chars.length)]; return n; }
