import * as vscode from 'vscode';
import { buildNodeDetails } from '../opencode/buildSessionViewModel';
import { buildTraceGraphViewModel } from '../opencode/buildTraceGraphViewModel';
import type { NormalizedOpenCodeSession } from '../opencode/model';
import { isWebviewToExtensionMessage } from '../webview/openCodeSessionTrace/model';
import { OpenCodeSessionTraceState } from './openCodeSessionTraceState';
import { renderOpenCodeSessionTraceHtml } from './renderOpenCodeSessionTrace';

export class OpenCodeSessionTracePanel { private static current: OpenCodeSessionTracePanel | undefined; private session?: NormalizedOpenCodeSession; private hideReasoning = true; private readonly state = new OpenCodeSessionTraceState(); private constructor(private readonly context: vscode.ExtensionContext, private readonly panel: vscode.WebviewPanel) { panel.onDidDispose(() => { if (OpenCodeSessionTracePanel.current === this) OpenCodeSessionTracePanel.current = undefined; }); panel.webview.onDidReceiveMessage(async (msg: unknown) => this.handle(msg)); }
  static show(context: vscode.ExtensionContext, session: NormalizedOpenCodeSession, rawUri: vscode.Uri, hideReasoning: boolean): void { if (!this.current) { const scriptRoot = vscode.Uri.joinPath(context.extensionUri, 'dist', 'webview'); this.current = new OpenCodeSessionTracePanel(context, vscode.window.createWebviewPanel('skillMdInspector.openCodeTrace', 'OpenCode Session Trace', vscode.ViewColumn.Beside, { enableScripts: true, retainContextWhenHidden: true, localResourceRoots: [scriptRoot] })); this.current.panel.webview.html = this.current.html(); } this.current.session = session; this.current.hideReasoning = hideReasoning; this.current.state.setRawUri(rawUri); this.current.panel.title = `OpenCode Trace: ${session.title}`; this.current.panel.reveal(vscode.ViewColumn.Beside); void this.current.postInitialize(); }
  private async handle(msg: unknown): Promise<void> { if (!isWebviewToExtensionMessage(msg)) return; if (msg.type === 'ready') { await this.postInitialize(); return; } if (!this.session) return; if (msg.type === 'requestNodeDetails') { const details = buildNodeDetails(this.session, msg.nodeId); await this.panel.webview.postMessage(details ? { type: 'nodeDetails', nodeId: msg.nodeId, details } : { type: 'showError', message: 'Node not found.' }); } else if (msg.type === 'requestPathNodeDetails') { const path = buildTraceGraphViewModel(this.session, this.hideReasoning).path; const details = path?.nodes.find((node) => node.id === msg.pathNodeId); await this.panel.webview.postMessage(details ? { type: 'pathNodeDetails', pathNodeId: msg.pathNodeId, details } : { type: 'showError', message: 'Path node not found.' }); } else if (msg.type === 'openRawSession') { const rawUri = this.state.getRawUri(); if (rawUri) await vscode.commands.executeCommand('vscode.open', rawUri); else await this.panel.webview.postMessage({ type: 'showError', message: 'No raw OpenCode session URI is available.' }); } else if (msg.type === 'copyText') await vscode.env.clipboard.writeText(msg.value); else if (msg.type === 'openSkill' || msg.type === 'openSkillReport') { const allowed = new Set(this.session.skills.flatMap((s) => s.matchingSkills.flatMap((m) => m.candidates.map((c) => c.uri)))); if (!allowed.has(msg.uri)) return; const uri = vscode.Uri.parse(msg.uri); if (msg.type === 'openSkill') await vscode.commands.executeCommand('vscode.open', uri); else await vscode.commands.executeCommand('skillMdInspector.showSkillReport', uri); } }
  private async postInitialize(): Promise<void> { if (!this.session) return; await this.panel.webview.postMessage({ type: 'initialize', model: buildTraceGraphViewModel(this.session, this.hideReasoning) }); }
  private html(): string { const nonce = createNonce(); const script = this.panel.webview.asWebviewUri(vscode.Uri.joinPath(this.context.extensionUri, 'dist', 'webview', 'openCodeSessionTrace.js')); const style = this.panel.webview.asWebviewUri(vscode.Uri.joinPath(this.context.extensionUri, 'dist', 'webview', 'openCodeSessionTrace.css')); return renderOpenCodeSessionTraceHtml(script.toString(), style.toString(), this.panel.webview.cspSource, nonce); }
}
function createNonce(): string { const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'; let n = ''; for (let i = 0; i < 32; i++) n += chars[Math.floor(Math.random() * chars.length)]; return n; }
