import type { SessionViewModel } from '../opencode/model';
import { escapeHtml } from '../opencode/util';

export function renderOpenCodeSessionReportHtml(model: SessionViewModel, cspSource: string): string {
  const cards = [['Messages', model.metrics.messageCount], ['Steps', model.metrics.stepCount], ['Tool calls', model.metrics.toolCallCount], ['Skill calls', model.metrics.skillCallCount], ['Errors', model.metrics.toolErrorCount], ['Cost', model.metrics.totalCost ?? '—'], ['Input tokens', model.metrics.inputTokens ?? '—'], ['Output tokens', model.metrics.outputTokens ?? '—'], ['Reasoning tokens', model.metrics.reasoningTokens ?? '—'], ['Cache tokens', (model.metrics.cacheReadTokens ?? 0) + (model.metrics.cacheWriteTokens ?? 0)]];
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${cspSource}; style-src 'unsafe-inline' ${cspSource};"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css()}</style><title>${escapeHtml(model.session.title)}</title></head><body><header><h1>${escapeHtml(model.session.title)}</h1><p>${escapeHtml([model.session.id, model.session.version && `OpenCode ${model.session.version}`, model.session.provider, model.session.model, model.session.agent].filter(Boolean).join(' · '))}</p><p>Sanitization: <strong>${escapeHtml(model.session.sanitization)}</strong></p></header><aside class="note">Actions shown after a skill load are temporal observations. The session export does not prove that a specific SKILL.md rule caused an action. The OpenCode export format is an internal evolving format.</aside>${model.session.sanitization === 'likely-sanitized' ? '<aside class="warn">This export appears sanitized; detailed trajectory analysis may be incomplete.</aside>' : ''}<section class="cards">${cards.map(([k,v]) => `<article><b>${escapeHtml(k)}</b><span>${escapeHtml(v)}</span></article>`).join('')}</section><section><h2>Compatibility diagnostics</h2>${model.diagnostics.length ? `<ul>${model.diagnostics.map((d) => `<li><b>${escapeHtml(d.severity)}</b> ${escapeHtml(d.code)} ${escapeHtml(d.path ?? '')}: ${escapeHtml(d.message)}</li>`).join('')}</ul>` : '<p>No diagnostics.</p>'}</section><section><h2>Loaded skills</h2><table><thead><tr><th>Skill</th><th>Status</th><th>Duration</th><th>Temporal segment</th><th>Matching SKILL.md</th></tr></thead><tbody>${model.skills.map((s) => `<tr><td>${escapeHtml(s.skillName ?? 'Unknown')}</td><td>${escapeHtml(s.status)}</td><td>${escapeHtml(s.end && s.start ? `${s.end - s.start} ms` : '—')}</td><td>${s.followingNodeIds.length}</td><td>${escapeHtml(s.matchingSkills.map((m) => m.status).join(', ') || 'none')}</td></tr><tr><td colspan="5"><b>Actions observed after skill load:</b> ${escapeHtml(Object.entries(s.actionSummary).map(([k,v]) => `${k} × ${v}`).join(', ') || 'none')}</td></tr>`).join('')}</tbody></table></section><section><h2>Ordered trajectory</h2>${renderChildren(model, 'session')}</section></body></html>`;
}
function renderChildren(model: SessionViewModel, parentId: string): string { const children = model.nodes.filter((n) => n.parentId === parentId).sort((a,b)=>a.sourceOrder-b.sourceOrder); if (!children.length) return ''; return `<ol>${children.map((n) => `<li><details ${n.kind !== 'reasoning' ? 'open' : ''}><summary><span class="kind">${escapeHtml(n.kind)}</span> ${escapeHtml(n.label)} ${n.status ? `<em>${escapeHtml(n.status)}</em>` : ''}</summary>${n.preview ? `<pre>${escapeHtml(n.preview)}</pre>` : ''}${n.incomplete ? '<p class="warn">Incomplete step</p>' : ''}${renderChildren(model, n.id)}</details></li>`).join('')}</ol>`; }
function css(): string { return `body{font-family:var(--vscode-font-family);color:var(--vscode-foreground);background:var(--vscode-editor-background);padding:1.5rem}h1{margin-bottom:.2rem}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:.75rem}.cards article{border:1px solid var(--vscode-panel-border);padding:.75rem;border-radius:6px}.cards span{display:block;font-size:1.4em}table{border-collapse:collapse;width:100%}td,th{border:1px solid var(--vscode-panel-border);padding:.4rem;text-align:left}pre{white-space:pre-wrap;max-height:18rem;overflow:auto;background:var(--vscode-textCodeBlock-background);padding:.5rem}.note{border-left:4px solid var(--vscode-notificationsInfoIcon-foreground);padding:.6rem}.warn{border-left:4px solid var(--vscode-notificationsWarningIcon-foreground);padding:.6rem}.kind{font-family:monospace}`; }
