import type { CompactNodeViewModel, NodeDetailsViewModel, SessionViewModel } from '../../opencode/model';
import type { ExtensionToWebviewMessage, WebviewToExtensionMessage } from './model';
import './styles.css';

declare function acquireVsCodeApi(): { postMessage(message: WebviewToExtensionMessage): void };
const vscode = acquireVsCodeApi();
let model: SessionViewModel | undefined; let selected = '';
window.addEventListener('message', (event: MessageEvent<ExtensionToWebviewMessage>) => { const msg = event.data; if (msg.type === 'initialize') { model = msg.model; render(); const first = model.nodes[0]; if (first) select(first.id); } else if (msg.type === 'nodeDetails') renderDetails(msg.details); else if (msg.type === 'showError') alert(msg.message); });
function el<K extends keyof HTMLElementTagNameMap>(tag: K, text?: string): HTMLElementTagNameMap[K] { const node = document.createElement(tag); if (text) node.textContent = text; return node; }
function render(): void { if (!model) return; document.body.textContent = ''; const h = el('header'); h.append(el('h1', model.session.title)); const s = el('div'); s.className='summary'; [`OpenCode ${model.session.version ?? 'unknown'}`, `${model.session.provider ?? 'provider'} / ${model.session.model ?? 'model'}`, `${model.metrics.toolCallCount} tools`, `${model.metrics.skillCallCount} skills`, `${model.metrics.toolErrorCount} errors`, model.session.sanitization].forEach((x)=>s.append(el('span', x))); h.append(s); document.body.append(h); const filters = el('div'); filters.className='filters'; const search = el('input'); search.placeholder='Search'; search.addEventListener('input', debounce(renderPanes, 200)); const kind = el('select'); ['all','user-message','assistant-message','step','skill','tool','reasoning','text','file','error','unknown'].forEach((k)=>{ const o=el('option',k); o.value=k; kind.append(o); }); kind.addEventListener('change', renderPanes); filters.append(kind, search, checkbox('Skills only','skills'), checkbox('Hide reasoning','hideReasoning'), checkbox('Hide successful tools','hideSuccess')); document.body.append(filters); const main = el('main'); main.innerHTML = '<section class="pane" id="outline" role="tree" aria-label="Session outline"></section><section class="pane" id="timeline"></section><section class="pane" id="details"><p>Select a node.</p></section>'; document.body.append(main); renderPanes(); }
function checkbox(label: string, id: string): HTMLElement { const l=el('label'); const c=el('input') as HTMLInputElement; c.type='checkbox'; c.id=id; if (id==='hideReasoning') c.checked=!!model?.hideReasoningByDefault; c.addEventListener('change', renderPanes); l.append(c, document.createTextNode(` ${label}`)); return l; }
function filtered(): CompactNodeViewModel[] { if (!model) return []; const q=(document.querySelector('input') as HTMLInputElement)?.value.toLowerCase() ?? ''; const k=(document.querySelector('select') as HTMLSelectElement)?.value ?? 'all'; const skills=(document.getElementById('skills') as HTMLInputElement)?.checked; const hideR=(document.getElementById('hideReasoning') as HTMLInputElement)?.checked; const hideS=(document.getElementById('hideSuccess') as HTMLInputElement)?.checked; return model.nodes.filter((n)=> (!skills || n.kind==='skill') && (!hideR || n.kind!=='reasoning') && (!hideS || !(n.kind==='tool' && n.status==='completed')) && (k==='all' || (k==='error' ? n.status==='error' : n.kind===k)) && (!q || `${n.label} ${n.preview ?? ''} ${n.toolName ?? ''} ${n.skillName ?? ''}`.toLowerCase().includes(q))); }
function renderPanes(): void { const outline=document.getElementById('outline'); const timeline=document.getElementById('timeline'); if (!outline||!timeline||!model) return; outline.textContent=''; timeline.textContent=''; const visible=new Set(filtered().map((n)=>n.id)); for (const n of model.nodes.filter((x)=>x.parentId==='session')) renderTreeNode(n, outline, 0, visible); const timed=model.nodes.filter((n)=>n.start!==undefined); const min=Math.min(...timed.map((n)=>n.start ?? 0)); const max=Math.max(...timed.map((n)=>n.end ?? n.start ?? 0)); for (const n of model.nodes.filter((x)=>visible.has(x.id))) { const row=el('div'); row.className='timeline-row'; row.append(el('button', n.label)); row.querySelector('button')?.addEventListener('click',()=>select(n.id)); const bar=el('div'); if (n.start!==undefined && max>min) { const inner=el('div'); inner.className='bar'; inner.style.marginLeft=`${(((n.start-min)/(max-min))*100).toFixed(2)}%`; inner.style.width=`${Math.max(1,(((n.end??n.start)-n.start)/(max-min))*100).toFixed(2)}%`; bar.append(inner); } else bar.append(el('span','untimed')); row.append(bar, el('span', n.status ?? n.kind)); timeline.append(row); } }
function renderTreeNode(n: CompactNodeViewModel, parent: HTMLElement, depth: number, visible: Set<string>): void { if (!model) return; const descendants=n.children.some((id)=>visible.has(id)); if (!visible.has(n.id) && !descendants) return; const b=el('button', `${'  '.repeat(depth)}${n.label}`); b.className=`node ${n.kind} ${n.status==='error'?'error':''} ${n.id===selected?'selected':''}`; b.setAttribute('role','treeitem'); b.tabIndex=0; b.addEventListener('click',()=>select(n.id)); b.addEventListener('keydown',(e)=>{ if(e.key==='Enter') select(n.id); }); parent.append(b); n.children.map((id)=>model!.nodes.find((x)=>x.id===id)).filter((x): x is CompactNodeViewModel=>!!x).forEach((c)=>renderTreeNode(c,parent,depth+1,visible)); }
function select(id: string): void { selected=id; vscode.postMessage({ type: 'requestNodeDetails', nodeId: id }); renderPanes(); }
function renderDetails(d: NodeDetailsViewModel): void { const root=document.getElementById('details'); if(!root) return; root.textContent=''; root.append(el('h2', d.title)); if(d.warning) root.append(el('p', d.warning)); for(const f of d.fields){ const p=el('p'); p.append(el('b', `${f.label}: `), document.createTextNode(f.value)); root.append(p); } if(d.matchingSkills?.length){ root.append(el('h3','Matching SKILL.md candidates')); for(const c of d.matchingSkills){ const b=el('button', c.path); b.addEventListener('click',()=>vscode.postMessage({type:'openSkill', uri:c.uri})); root.append(b); } } if(d.followingNodes?.length){ root.append(el('h3','Actions observed after skill load')); d.followingNodes.forEach((n)=>root.append(el('p', n.label))); } if(d.json){ root.append(el('h3','Raw JSON')); root.append(el('pre', d.json)); } }
function debounce(fn:()=>void, ms:number):()=>void { let t:number|undefined; return () => { window.clearTimeout(t); t=window.setTimeout(fn,ms); }; }
