import { describe, expect, it } from 'vitest';
import { collapseVisibleTimelineEvents, createInitialTimelineState, expandVisibleTimelineEvents, setTimelineFilter, setTimelineSearchQuery, toggleTimelineEvent, visibleTimelineEvents } from '../../src/webview/openCodeSessionReport/state';
import type { OpenCodeTimelineEvent, OpenCodeTimelineViewModel } from '../../src/opencode/timelineViewModel';
const ev = (id: string, kind: OpenCodeTimelineEvent['kind'], category: OpenCodeTimelineEvent['category'], searchText = id): OpenCodeTimelineEvent => ({ id, kind, category, sourceOrder: 1, label: id, expandable: true, initiallyExpanded: false, hasLazyDetails: false, fileReferences: [], searchText });
const events = [ev('tool','tool','tool','read src/auth.ts'), ev('skill','skill','tool','tester'), ev('reason','reasoning','reasoning','think'), ev('error','tool','error','boom'), ev('diff','patch','diff','src/file'), ev('text','assistant-message','text','hello'), ev('sub','subtask','subtask','audit leak')];
const model = { initialState: { activeFilter: 'all', expandedEventIds: ['error'] }, diagnosticsSummary: { error: 0 }, session: { sanitization: 'not-detected' }, events } as unknown as OpenCodeTimelineViewModel;
describe('timeline state helpers', () => {
  it('filters, searches, toggles, and preserves hidden expansion state', () => { let state = createInitialTimelineState(model); expect(state.sessionDetailsExpanded).toBe(false); expect(state.expandedEventIds.has('error')).toBe(true); state = toggleTimelineEvent(state, 'tool'); expect(state.expandedEventIds.has('tool')).toBe(true); state = setTimelineFilter(state, 'tools'); state = setTimelineSearchQuery(state, 'read'); expect(visibleTimelineEvents(events, state).map((e)=>e.id)).toEqual(['tool']); state = expandVisibleTimelineEvents(state, events); expect(state.expandedEventIds.has('tool')).toBe(true); expect(state.expandedEventIds.has('error')).toBe(true); state = collapseVisibleTimelineEvents(state, events); expect(state.expandedEventIds.has('tool')).toBe(false); expect(state.expandedEventIds.has('error')).toBe(true); });
  it('separates skills from tools and combines skills with search and errors', () => { let state = createInitialTimelineState(model); expect(visibleTimelineEvents(events, state).map((e)=>e.id)).toContain('tool'); expect(visibleTimelineEvents(events, state).map((e)=>e.id)).toContain('skill'); state = setTimelineFilter(state, 'tools'); expect(visibleTimelineEvents(events, state).map((e)=>e.id)).toEqual(['tool','error']); state = setTimelineFilter(state, 'skills'); expect(visibleTimelineEvents(events, state).map((e)=>e.id)).toEqual(['skill']); state = setTimelineSearchQuery(state, 'tester'); expect(visibleTimelineEvents(events, state).map((e)=>e.id)).toEqual(['skill']); state = expandVisibleTimelineEvents(state, events); expect(state.expandedEventIds.has('skill')).toBe(true); expect(state.expandedEventIds.has('tool')).toBe(false); state = collapseVisibleTimelineEvents(state, events); expect(state.expandedEventIds.has('skill')).toBe(false); state = setTimelineFilter(state, 'errors'); state = setTimelineSearchQuery(state, ''); expect(visibleTimelineEvents([...events, ev('failed-skill','skill','error','bad')], state).map((e)=>e.id)).toEqual(['error','failed-skill']); });
});
