import { describe, expect, it } from 'vitest';
import { buildOpenCodeTimelineEventDetails, buildOpenCodeTimelineViewModel, latencyRatio, tokenTotal } from '../../src/opencode/timelineViewModel';
import type { NormalizedOpenCodeSession, TrajectoryNode } from '../../src/opencode/model';

function node(partial: Partial<TrajectoryNode> & Pick<TrajectoryNode, 'id' | 'kind' | 'sourceOrder' | 'label'>): TrajectoryNode { return { children: [], ...partial }; }
function session(nodes: TrajectoryNode[]): NormalizedOpenCodeSession { const rawByReference = new Map<string, unknown>(); for (const n of nodes) if (n.rawReference) rawByReference.set(n.rawReference, { state: { input: { filePath: 'src/auth.ts' }, output: 'ok\n'.repeat(20), error: n.status === 'error' ? { message: 'boom' } : undefined }, patch: '<script>alert(1)</script>' }); return { id: 'ses_1', title: '<img onerror=alert(1)>', version: '0.6.3', model: 'claude', provider: 'anthropic', agent: 'build', created: 1000, updated: 7000, details: { variant: 'x', summary: { files: 2, additions: 10, deletions: 3 } }, sanitization: 'not-detected', diagnostics: [{ severity: 'warning', code: 'x', message: '<script>', path: '$' }], nodes: [node({ id: 'session', kind: 'session', sourceOrder: 0, label: 'root', children: nodes.map((n)=>n.id) }), ...nodes], rootNodeId: 'session', rawByReference, messages: [], metrics: { messageCount: 2, userMessageCount: 1, assistantMessageCount: 1, stepCount: 1, toolCallCount: 2, toolErrorCount: 1, assistantErrorCount: 0, errorCount: 1, skillCallCount: 1, uniqueLoadedSkills: 1, retryCount: 1, compactionCount: 1, unknownPartCount: 1, totalCost: 0.2, inputTokens: 10, outputTokens: 5, reasoningTokens: 2, cacheReadTokens: 5, cacheWriteTokens: 1, sessionDurationMs: 6000 }, skills: [{ skillName: 'tester', status: 'completed', followingNodeIds: ['tool'], relationship: 'temporal', actionSummary: { read: 1 }, matchingSkills: [{ status: 'single', candidates: [] }] }] }; }
const nodes = [
  node({ id: 'u', kind: 'user-message', sourceOrder: 1, label: 'user message', start: 1000, preview: 'hello src/auth.ts' }),
  node({ id: 'a-step', kind: 'step', sourceOrder: 2, label: 'Step', start: 1100, end: 3000, durationMs: 1900, details: { finish: 'tool-calls', cost: 0.03, tokens: { input: 3, output: 1, reasoning: 2 } } }),
  node({ id: 'r', kind: 'reasoning', sourceOrder: 3, label: 'reason', start: 1200, end: 1300, durationMs: 100, preview: 'Think' }),
  node({ id: 't', kind: 'tool', sourceOrder: 4, label: 'read src/auth.ts', start: 1400, end: 1500, durationMs: 100, status: 'completed', toolName: 'read', rawReference: 't', details: { state: { input: { filePath: 'src/auth.ts' } } } }),
  node({ id: 's', kind: 'skill', sourceOrder: 5, label: 'Skill: tester', start: 1600, end: 1700, durationMs: 100, skillName: 'tester', rawReference: 's' }),
  node({ id: 'e', kind: 'tool', sourceOrder: 6, label: 'bash error', start: 1800, end: 2200, durationMs: 400, status: 'error', toolName: 'bash', preview: 'boom', rawReference: 'e' }),
  node({ id: 'retry', kind: 'retry', sourceOrder: 7, label: 'retry', start: 2300, rawReference: 'retry', preview: 'APIError' }),
  node({ id: 'p', kind: 'patch', sourceOrder: 8, label: 'patch', start: 2400, rawReference: 'p', details: { hash: 'abc', files: [{ additions: 10, deletions: 3 }] } }),
  node({ id: 'sub', kind: 'subtask', sourceOrder: 9, label: 'Subtask: audit', start: 2500, preview: 'audit leak', rawReference: 'sub' }),
  node({ id: 'agent', kind: 'agent', sourceOrder: 10, label: 'Agent: build', start: 2600, rawReference: 'agent' }),
  node({ id: 'c', kind: 'compaction', sourceOrder: 11, label: 'Compaction', start: 2700 }),
  node({ id: 'x', kind: 'unknown', sourceOrder: 12, label: 'Unknown: future', rawReference: 'x', preview: '<img onerror=1>' }),
  node({ id: 'a', kind: 'assistant-message', sourceOrder: 13, label: 'assistant message', start: 5000, end: 7000, durationMs: 2000, preview: 'done' }),
];

describe('OpenCode timeline view model', () => {
  it('keeps stable source order and maps event categories and filter counts', () => { const vm = buildOpenCodeTimelineViewModel(session(nodes)); expect(vm.events.map((e)=>e.id)).toEqual(nodes.map((n)=>n.id)); expect(vm.events.find((e)=>e.id==='u')).toMatchObject({ kind: 'user-message', category: 'text', elapsedMs: 0 }); expect(vm.events.find((e)=>e.id==='r')).toMatchObject({ category: 'reasoning', initiallyExpanded: false }); expect(vm.events.find((e)=>e.id==='e')).toMatchObject({ category: 'error', initiallyExpanded: true }); expect(vm.events.find((e)=>e.id==='p')?.diffSummary).toMatchObject({ additions: 10, deletions: 3 }); expect(vm.events.find((e)=>e.id==='x')).toMatchObject({ kind: 'unknown' }); expect(vm.filters).toMatchObject({ all: 13, tools: 3, skills: 1, reasoning: 1, errors: 2, diffs: 1, text: 2, subtasks: 2 }); });
  it('calculates deterministic metrics and formatting inputs without NaN', () => { const vm = buildOpenCodeTimelineViewModel(session(nodes)); expect(vm.metrics.totalTokens).toBe(17); expect(vm.metrics.cachedShare).toBeCloseTo(5 / 15); expect(tokenTotal()).toBeUndefined(); expect(tokenTotal(1, undefined, 2)).toBe(3); });
  it('handles missing timestamps and negative durations without fabrication', () => { const vm = buildOpenCodeTimelineViewModel(session([node({ id: 'm', kind: 'tool', sourceOrder: 1, label: 'missing', durationMs: -1 })])); expect(vm.events[0].elapsedMs).toBeUndefined(); expect(vm.events[0].durationMs).toBeUndefined(); });
  it('normalizes latency against p95 with a visible minimum', () => { expect(latencyRatio(1, 1000)).toBe(0.08); expect(latencyRatio(2000, 1000)).toBe(1); expect(latencyRatio(-1, 1000)).toBeUndefined(); });
  it('returns bounded lazy details for the current known event only', () => { const s = session(nodes); const details = buildOpenCodeTimelineEventDetails(s, 't', 80); expect(details?.input).toContain('filePath'); expect(details?.raw).toContain('truncated'); expect(buildOpenCodeTimelineEventDetails(s, 'missing', 10)).toBeUndefined(); });
});
